name: Bug Report
description: Report a bug or unexpected behavior in SPRINT
title: "[BUG] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve SPRINT! Don't worry about filling everything out perfectly - just share what you can.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Tell us what went wrong
      placeholder: Describe the bug in your own words...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened instead?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if known)
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: dropdown
    id: workflow_step
    attributes:
      label: Which workflow step? (optional)
      options:
        - Ideate
        - Visualize
        - Define
        - Build
        - Test
        - Deploy
        - Not sure / Other
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: SPRINT version (optional)
      placeholder: "e.g., 1.0.0"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Screenshots, error messages, or other context welcome!
    validations:
      required: false
