name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[DOCS] "
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        Help us make our docs better! Let us know what's confusing or missing.

  - type: textarea
    id: issue
    attributes:
      label: What needs improvement?
      description: Tell us what's unclear, missing, or incorrect
      placeholder: I couldn't figure out how to...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Where did you look? (optional)
      description: URL or section name
      placeholder: "e.g., Figma setup guide"
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestions (optional)
      description: How could we make it clearer?
    validations:
      required: false
