name: Feature Request
description: Suggest a new feature or enhancement for SPRINT
title: "[FEATURE] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas! Share as much or as little detail as you'd like.

  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe your idea or the problem you're trying to solve
      placeholder: I wish SPRINT could...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: How would you use it?
      description: Help us understand your workflow
      placeholder: This would help me when...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category (optional)
      options:
        - Ideate
        - Visualize / Design
        - Define / Architecture
        - Build / Code generation
        - Test / QA
        - Deploy
        - Figma integration
        - Backend integrations
        - Mobile
        - Web
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Mockups, examples, or references welcome!
    validations:
      required: false
