name: Model Behavior Issue
description: Report unexpected AI behavior or code generation issues
title: "[MODEL] "
labels:
  - model
body:
  - type: markdown
    attributes:
      value: |
        AI doesn't always get it right - let us know when something's off so we can improve!

  - type: textarea
    id: what_happened
    attributes:
      label: What did the AI do?
      description: Describe the unexpected behavior or output
      placeholder: The AI generated code that...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: I expected it to...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: What were you trying to do? (optional)
      description: Your inputs, prompts, or Figma designs
      placeholder: I was trying to build a login screen with...
    validations:
      required: false

  - type: dropdown
    id: workflow_step
    attributes:
      label: Which step? (optional)
      options:
        - Ideate
        - Visualize
        - Define
        - Build
        - Test
        - Deploy
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Screenshots, code samples, or other details welcome!
    validations:
      required: false
